sonar.projectKey=NikitaSukharev_python-project-386
sonar.organization=NikitaSukharev

sonar.sources=backend,frontend
sonar.exclusions=frontend/node_modules/**,frontend/dist/**,frontend/playwright-report/**,frontend/test-results/**
